/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day07squarefractal;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author ewuzhou
 */
public class SquareFractalPanel extends javax.swing.JPanel {

    /**
     * Creates new form SquareJPanel
     */
    public SquareFractalPanel() {
        //initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g){   //canibas similar
        super.paintComponent(g);  // components of graphics
        Graphics2D g2d = (Graphics2D)g.create();  
        
        int x1 = 10; 
        int y1 = 10;
        int x2 = 10;
        int y2 = getHeight() -10; 
        int x3 = getWidth() -10; 
        int y3 = 10;    
        int x4 = getWidth() -10;
        int y4 = getHeight() -10;
        
        g2d.drawLine(x1, y1, x3, y3);
        g2d.drawLine(x1, y1, x2, y2);
        g2d.drawLine(x2, y2, x4, y4);
        g2d.drawLine(x4, y4, x3, y3);
        
        drawSquareFractal(g2d, x1, y1, x2, y2, x3, y3, x4, y4);
    }
    
    private void drawSquareFractal(Graphics2D g2d, int x1, int y1, int x2, int y2, int x3, int y3, int x4, int y4){
        
        double dist = x3-x1;
        int side = x3-x1;
        
        if(dist < 50) return;
        
        int x13l = (x1+x3)/2-side/10;
        int x13r = (x1+x3)/2+side/10;
        
        int x24l = (x2+x4)/2-side/10;
        int x24r = (x2+x4)/2+side/10;
        
        int y12u = (y1+y2)/2-side/10;
        int y12d = (y1+y2)/2+side/10;
        
        int y34u = (y3+y4)/2-side/10;
        int y34d = (y3+y4)/2+side/10;
        
        //g2d.drawLine(x13l, y1, x13l+5, y1+5);
        //g2d.drawLine(x24l, y2, x24l+5, y2+5);
        //g2d.drawLine(x1, y12u,x1+5, y12u+5);
        //g2d.drawLine(x3, y34u, x3+5, y34u+5);

        g2d.drawLine(x13l, y1, x13l, y12u);
        g2d.drawLine(x1, y12u, x13l, y12u);
        
        g2d.drawLine(x13r, y3, x13r, y34u);
        g2d.drawLine(x13r, y34u, x3, y34u);
        
        g2d.drawLine(x1, y12d, x24l, y12d);
        g2d.drawLine(x13l, y12d, x24l, y2);
        
        g2d.drawLine(x24r, y34d, x4, y34d);
        g2d.drawLine(x24r, y4, x13r, y34d);
        
        drawSquareFractal(g2d, x1, y1, x1, y12u, x13l, y1, x13l, y12u);
        drawSquareFractal(g2d, x13r, y3, x13r, y34u, x3, y3, x3, y34u);
        drawSquareFractal(g2d, x2, y12d, x2, y2, x13l, y12d, x13l, y2);
        drawSquareFractal(g2d, x13r, y34d, x13r, y4, x4, y34d, x4, y4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
