/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06firstfractal;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author ewuzhou
 */
public class FractalPanel extends javax.swing.JPanel {

    /**
     * Creates new form FractalPanel
     */
    public FractalPanel() {
        //initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g){   //canibas similar
        super.paintComponent(g);  // components of graphics
        Graphics2D g2d = (Graphics2D)g.create();  
        g2d.drawLine(10, getHeight()/10, getWidth()-10, getHeight()/10); // top left corner, 
        drawFractal(g2d, 10, getWidth()-10, getHeight()/10, getHeight()/10);  
    }
    
    
    private void drawFractal(Graphics2D g2d, int fromX, int toX, int levelY, int stepY) {
        // 1. condition when the recursion ends
        int totalWidth = toX - fromX;
        if(totalWidth < 3) return;  // less than 3 pixels
        // 2. draws the two lines
        levelY += stepY;   // distance between two line in vertical
        g2d.drawLine(fromX, levelY, fromX+totalWidth/3, levelY);
        g2d.drawLine(toX-totalWidth/3, levelY, toX, levelY);
        // 3. make two recursive calls, one for each line you just draw
        drawFractal(g2d, fromX, fromX + totalWidth/3, levelY, stepY);
        drawFractal(g2d, toX-totalWidth/3, toX, levelY, stepY);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
