/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day07thornyfractal;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author ewuzhou
 */
public class ThornyFractalPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThornyFractalPanel
     */
    public ThornyFractalPanel() {
        //initComponents();
    }

    @Override
    protected void paintComponent(Graphics g){   //canibas similar
        super.paintComponent(g);  // components of graphics
        Graphics2D g2d = (Graphics2D)g.create();  
        
        int x1 = 10; 
        int y1 = getHeight() -50;
        int x2 = getWidth()-10;
        int y2 = getHeight() -50;
        
        int x3 = (2*x1+x2)/3;
        int x4 = (2*x2+x1)/3;
        int x5 = (x1+x2)/2;
        
        int y5 = y1 - (x2-x1)*4/15;
        
        g2d.drawLine(x1, y1, x2, y2);
        
        drawThornyFractal(g2d, x1, y1, x2, y2);
    }
    
    private void drawThornyFractal(Graphics2D g2d, int x1, int y1, int x2, int y2){
        
        double dist = Math.sqrt((x1 - x2)*(x1 - x2) + (y1 - y2)*(y1 - y2));
        if(dist < 10) return;
        
        int x3 = (2*x1+x2)/3;
        int x4 = (2*x2+x1)/3;
        int x5 = (x1+x2)/2;
        
        int y3 = (2*y1+y2)/3;
        int y4 = (2*y2+y1)/3;
        int y5 = y1 - (x2-x1)*4/15;
        
        g2d.drawLine(x3, y3, x5, y5);
        g2d.drawLine(x4, y4, x5, y5);
        
        drawThornyFractal(g2d, x1, y1, x3, y3);
        drawThornyFractal(g2d, x4, y4, x2, y2);
        
        drawThornyLeftFractal(g2d, x3, y3, x5, y5);
        drawThornyRightFractal(g2d, x4, y4, x5, y5);
    }
    
    private void drawThornyLeftFractal(Graphics2D g2d, int x1, int y1, int x2, int y2){
        
        double dist = Math.sqrt((x1 - x2)*(x1 - x2) + (y1 - y2)*(y1 - y2));
        if(dist < 10) return;
        
        int x3 = (2*x1+x2)/3;
        int x4 = (2*x2+x1)/3;
        int x5 = x1;
        
        int y3 = (2*y1+y2)/3;
        int y4 = (2*y2+y1)/3;
        int y5 = (2*y2+y1)/3;
        
        g2d.drawLine(x3, y3, x5, y5);
        g2d.drawLine(x5, y5, x4, y4);
        
        drawThornyLeftFractal(g2d, x5, y5, x3, y3);
        drawThornyFractal(g2d, x5, y5, x4, y4);
    }
    
    private void drawThornyRightFractal(Graphics2D g2d, int x1, int y1, int x2, int y2){
        
        double dist = Math.sqrt((x1 - x2)*(x1 - x2) + (y1 - y2)*(y1 - y2));
        if(dist < 10) return;
        
        int x3 = (2*x1+x2)/3;
        int x4 = (2*x2+x1)/3;
        int x5 = x1;
        
        int y3 = (2*y1+y2)/3;
        int y4 = (2*y2+y1)/3;
        int y5 = (2*y2+y1)/3;
        
        g2d.drawLine(x3, y3, x5, y5);
        g2d.drawLine(x5, y5, x4, y4);
        
        drawThornyRightFractal(g2d, x5, y5, x3, y3);
        drawThornyFractal(g2d, x4, y4, x5, y5);
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
